services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  Tourze\TrainCategoryBundle\Command\:
    resource: '../../Command/'
  Tourze\TrainCategoryBundle\Controller\:
    resource: '../../Controller/'
  Tourze\TrainCategoryBundle\DataFixtures\:
    resource: '../../DataFixtures/'
  Tourze\TrainCategoryBundle\Procedure\:
    resource: '../../Procedure/'
  Tourze\TrainCategoryBundle\Repository\:
    resource: '../../Repository/'
  Tourze\TrainCategoryBundle\Service\:
    resource: '../../Service/'
